# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Machine Learning Blogs
email: sushe.shakya@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Machine Learning Blogs
baseurl: /awesome-ml-blogs # the subpath of your site, e.g. /blog
url: sushe-shakya.github.io # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: sushe_shakya
github_username:  sushe-shakya
author: 
  name: Sushil Shakya
  avatar: "/assets/images/ss.jpeg"
  bio: "Computer Engineer interested towards the field of AI"
  location: "United Kingdom"

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
paginate: 6
paginate_path: /page:num/

plugins:
  - jekyll-feed
  - jekyll-include-cache

# post configs
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
